# Generated by Django 3.2 on 2021-05-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeWatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('11/10', '11/10'), ('10/10', '10/10'), ('9/10', '9/10'), ('8/10', '8/10'), ('7/10', '7/10'), ('6/10', '6/10'), ('5/10', '5/10'), ('4/10', '4/10'), ('3/10', '3/10'), ('2/10', '2/10'), ('1/10', '1/10'), ('0/10', '0/10')], max_length=5)),
                ('watching', models.CharField(choices=[('Finished', 'Finished'), ('In process', 'In process'), ('Dropped', 'Dropped'), ('Plans to watch', 'Plans to watch')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='EurovisionCelebrities',
        ),
    ]
