# Generated by Django 3.2 on 2021-05-26 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_lab', '0002_auto_20210525_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='animewatching',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animewatching',
            name='rating',
            field=models.CharField(choices=[('11/10', '11/10'), ('10/10', '10/10'), ('9/10', '9/10'), ('8/10', '8/10'), ('7/10', '7/10'), ('6/10', '6/10'), ('5/10', '5/10'), ('4/10', '4/10'), ('3/10', '3/10'), ('2/10', '2/10'), ('1/10', '1/10'), ('0/10', '0/10'), ('--/10', '--/10')], max_length=5),
        ),
    ]
